### ISSUE TITLE
Contact Us - section not centered on 768px+

### ISSUE THREAD

**Issue by celineselee** [StarterHacks/sh-site#26]
<img width="782" alt="screenshot_2018-11-14__6_25_pm" src="https://user-images.githubusercontent.com/25260228/48519629-97112d80-e83b-11e8-90d4-f8a3cb6f2f5f.png">
<img width="1073" alt="screenshot_2018-11-14__6_32_pm" src="https://user-images.githubusercontent.com/25260228/48519654-ac865780-e83b-11e8-814b-45720e9b3caa.png">

**Comment by ahrarmonsur** [comment]
Done!
