### ISSUE TITLE
How It Works section - everything shifts a bit once you click on the slider 

### ISSUE THREAD

**Issue by celineselee** [StarterHacks/sh-site#28]
Here's a screenshot but it's not really obvious on the screenshot lol but if you check for yourself on the actual site it becomes a lot more obvious
<img width="631" alt="screenshot_2018-11-14__6_57_pm" src="https://user-images.githubusercontent.com/25260228/48520657-68955180-e83f-11e8-9eed-c7b438b04d73.png">

**Suggestion (?)**
In the design, the text is centered in the div. I implemented this with flexbox so whenever the height of the inner div changes everything shifts. 
We could fix the height of the inner div so it doesn't grow and shift

**Comment by ahrarmonsur** [comment]
Fixed. Was a combined issue of the incorrect image size for the blue picture, and incorrect min-height for how-it-works-desc section
