### ISSUE TITLE
[Safari] Why StarterHacks section letter spacing is too big for bolded parts

### ISSUE THREAD

**Issue by celineselee** [StarterHacks/sh-site#41]
<img width="699" alt="screenshot_2018-11-16__11_21_am" src="https://user-images.githubusercontent.com/25260228/48633760-f3866100-e991-11e8-85f1-49745442f910.png">

"You'll have a c c e s s ...  "

**Comment by ahrarmonsur** [comment]
Fixes by removing the bold formatting, as requested.
