### ISSUE TITLE
Some typos from one of my coworkers to review

### ISSUE THREAD

**Issue by cgada** [StarterHacks/sh-site#44]
"....Impact Partners who will not only bring meaningful problems for **you** to solve but **also** provide you with guidance and mentorship"

"Registration will act as a mingle session for participants **and Slack (the main communication platform for the event)** will have a channel for you to introduce yourself and find new friends"

"Subscribe today and **stay up-to-date** "

**Comment by cgada** [comment]
cc: @ahrarmonsur can you fix these when you get a chance?

**Comment by ahrarmonsur** [comment]
@cgada made the fix. Thank your coworker for me!
