### ISSUE TITLE
Apply Now modal should have a drop shadow instead of outline

### ISSUE THREAD

**Issue by celineselee** [StarterHacks/sh-site#46]
<img width="677" alt="starterhacks" src="https://user-images.githubusercontent.com/25260228/49602925-b80b0100-f957-11e8-89d7-5a274571e3d2.png">

design:
<img width="650" alt="starterhacks_web_design" src="https://user-images.githubusercontent.com/25260228/49603021-10da9980-f958-11e8-9296-a8e14b059f9a.png">

**Comment by ahrarmonsur** [comment]
FIXED

**Comment by ahrarmonsur** [comment]
<img width="879" alt="modal_dropshadow" src="https://user-images.githubusercontent.com/4240020/49634852-e9251900-f9cb-11e8-870e-871c56171d97.png">
