### ISSUE TITLE
Modal on mobile is too big 

### ISSUE THREAD

**Issue by celineselee** [StarterHacks/sh-site#48]
iPhone 5/SE size (320px) 
<img width="403" alt="starterhacks" src="https://user-images.githubusercontent.com/25260228/49603552-9743ab00-f959-11e8-925a-584403b12f86.png">

**Comment by ahrarmonsur** [comment]
FIXED
<img width="332" alt="small_screen_modal" src="https://user-images.githubusercontent.com/4240020/49634785-be3ac500-f9cb-11e8-95d4-f36ccc00e9c0.png">
